# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html
AWSTemplateFormatVersion: "2010-09-09"
#Optional
Description: "Describes this template"

# Optional
Parameters:
  # parameters allow us to specify values at run time
  Environment: # arbitrary
    Type: String
    Default: dev #Optional
    AllowedValues:
      - dev
      - stage
      - uat
      - prod

# Required
Resources:
  # list of AWS resources we want created or updated
  MyVPC: # logical ID
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

Mappings:
  # collection of nested key/value pairs
  # allows us to MAP one value to another value

Conditions:
  # statements that determine when a resource is created or when a property is defined
  # eg dev vs prod

Outputs:
  # declares values to be made readily available after creation/update
  # eg. explicitly show DNS endpoint of ELB or RDS instance
  MyVpcId: Ref: MyVPC