AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
    AllowedValues: ["dev", "stage", "uat", "prod"]

Mappings:

  AmazonLinux:
    us-east-2:
      x86: "ami-f63b1193"
      arm: "ami-ca3b11af"
    us-west-2:
      x86: "ami-f2d3638a"
      arm: "ami-74d8680c"

  UbuntuXenial:
    us-east-2:
      x86: "ami-6a003c0f"
      arm: "ami-2cfcc049"
    us-west-2:
      x86: "ami-db710fa3"
      arm: "ami-3b6a1443"

  InstanceTypeByEnvironment:
    type:
      dev: "t2.small"
      stage: "t2.large"
      uat: "c4.large"
      prod: "c5.4xlarge"


Resources:
  X86AmazonLinux:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [AmazonLinux, !Ref AWS::Region, "x86"]
      InstanceType: !FindInMap [InstanceTypeByEnvironment, "type", !Ref Environment]

  ArmUbuntuXenial:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [UbuntuXenial, !Ref AWS::Region, "arm"]
      InstanceType: !FindInMap [InstanceTypeByEnvironment, "type", !Ref Environment]
